version: '3.8'

services:
  app:
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
    #environment:
    # - PORT=${PORT}
    ports:
     - ${PORT}:${PORT}
    volumes:
     - ./src:/app/src
    depends_on:
     - db

  db: 
    image: db
    build: 
      context: .
      dockerfile: Dockerfile_db
    ports: 
      - ${PORT_POSTGRES}:${PORT_POSTGRES}
    restart: unless-stopped
    volumes:
     # - ~/apps/postgres:/var/lib/postgresql/data
      - ./data:/app/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
    
      - ${PORT_PGADMIN_DOCKER}:${PORT_PGADMIN_MAP}
    depends_on:
     - db
    #volumes:
    # - pgadmin-data:/data/pgadmin
     # - pgadmin-data:/app/data/pgadmin
    
#volumes:
 # db-data:
  #pgadmin-data:
  